name: IHub Actions
author: IHub
description: IHub GitHub Gradle Actions
branding:
  icon: box
  color: gray-dark
inputs:
  run:
    required: true
    description: Gradle Command
runs:
  using: composite
  steps:
    - name: Run with Gradle
      shell: bash
      run: |
        chmod +x gradlew
        ./gradlew ${{ inputs.run }} -PiHub.mavenAliYunEnabled=false
