name: "IHub Actions"
author: "IHub"
description: "IHub GitHub Actions"
branding:
  icon: "check"
  color: "gray-dark"
# inputs:
#   text:
#     required: false
#     description: "Text"
runs:
#   using: "composite"
  steps:
    - name: "Hello IHub"
      run: echo Hello, IHub!
