name: IHub Publish Actions
author: IHub
description: IHub GitHub Gradle Publish Actions
branding:
  icon: box
  color: gray-dark
inputs:
  repoUsername:
    required: true
    description: Repo Username
  repoPassword:
    required: true
    description: Repo Password
runs:
  using: composite
  steps:
    - name: Run with Gradle
      shell: bash
      run: |
        chmod +x gradlew
        ./gradlew publish
      env:
        REPO_USERNAME: ${{ inputs.repoUsername }}
        REPO_PASSWORD: ${{ inputs.repoPassword }}
