name: IHub Publish Actions
author: IHub
description: IHub GitHub Gradle Publish Actions
branding:
  icon: box
  color: gray-dark
inputs:
  repoUsername:
    required: true
    description: Repo Username
  repoPassword:
    required: true
    description: Repo Password
  release:
    required: false
    description: Is Release
    default: 'false'
  signingKeyId:
    required: false
    description: signingKeyId
  signingPassword:
    required: false
    description: signingPassword
  signingSecretKey:
    required: false
    description: signingSecretKey
runs:
  using: composite
  steps:
    - name: Run with Gradle
      env:
        REPO_USERNAME: ${{ inputs.repoUsername }}
        REPO_PASSWORD: ${{ inputs.repoPassword }}
        SIGNING_KEY_ID: ${{ inputs.signingKeyId }}
        SIGNING_PASSWORD: ${{ inputs.signingPassword }}
        SIGNING_SECRET_KEY: ${{ inputs.signingSecretKey }}
      shell: bash
      run: |
        chmod +x gradlew
        ./gradlew publish -DiHubPublish.publishDocs=${{ inputs.release }} -DiHubPublish.publishNeedSign=${{ inputs.release }}
